[project]
name = "rknazo"
version = "1.0.0"
description = ""
authors = [
    {name = "Ricky8955555", email = "rkmiao@duck.com"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "Apache-2.0"}
include = ["src/**/py.typed"]
